---
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:026090550003:task-definition/BG-TD:1"
        LoadBalancerInfo:
          ContainerName: "spring-container"
          ContainerPort: 8080
