version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - yum install -y jq maven
      - echo Logging in to Amazon ECR Public...
      - docker login -u AWS -p $(aws ecr-public get-login-password --region us-east-1) public.ecr.aws

      - REPO_NAME=spring
      - IMAGE_TAG=spring-app-fixed
      - PUBLIC_REPO_URI=public.ecr.aws/k2l2o0v7/$REPO_NAME

  build:
    commands:
      - echo Building the JAR file...
      - mvn clean install
      - echo Building the Docker image...
      - docker build -t $REPO_NAME .
      - docker tag $REPO_NAME:latest $PUBLIC_REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR Public...
      - docker push $PUBLIC_REPO_URI:$IMAGE_TAG
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"spring-cluster","imageUri":"%s:%s"}]' $PUBLIC_REPO_URI $IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yml
